{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "greeting",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d2lu5uitgraj3fieppzg3wa4o4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "greeting-1.0.jar",
          "url": "greeting-1.0.jar",
          "size": 2078,
          "sha512": "1da06821a7e629324b6250a93950fd299714348b30a16fa9ed266726579b434cc1b4812c3e1e6607164fbc4978755bd5669fc4ee1bbc06cfe7b4772d7b00f27c",
          "sha256": "cd536957ad1d276067830db151478373cf4a4784cf59cb11dbd472d122b80e",
          "sha1": "6d977ec05f91f215d8c7b395f79f499619c5613f",
          "md5": "ffb970e7344dbd8b8763366eebda4117"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "greeting-1.0.jar",
          "url": "greeting-1.0.jar",
          "size": 2078,
          "sha512": "1da06821a7e629324b6250a93950fd299714348b30a16fa9ed266726579b434cc1b4812c3e1e6607164fbc4978755bd5669fc4ee1bbc06cfe7b4772d7b00f27c",
          "sha256": "cd536957ad1d276067830db151478373cf4a4784cf59cb11dbd472d122b80e",
          "sha1": "6d977ec05f91f215d8c7b395f79f499619c5613f",
          "md5": "ffb970e7344dbd8b8763366eebda4117"
        }
      ]
    },
    {
      "name": "gradle7ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "greeting-1.0-gradle7.jar",
          "url": "greeting-1.0-gradle7.jar",
          "size": 2115,
          "sha512": "276c670fb26e1dfac54cf2f3e5552124fbace061cee0049b812701f9a2f85f933e6964c2f99b7871a02fb5c2df3aa05803425ef0ffec49f39bbae19fba076f38",
          "sha256": "6ec51ce9bf6e1e74503b65ca0945559639eac58a0a8048c75e53c1dce7321eb6",
          "sha1": "2a181b89e86ac649536f32e20e7d40838b767cbd",
          "md5": "5c8782bdc459e5f221e8c89b8e507714"
        }
      ],
      "capabilities": [
        {
          "group": "com.example",
          "name": "greeting",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "gradle7RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "greeting-1.0-gradle7.jar",
          "url": "greeting-1.0-gradle7.jar",
          "size": 2115,
          "sha512": "276c670fb26e1dfac54cf2f3e5552124fbace061cee0049b812701f9a2f85f933e6964c2f99b7871a02fb5c2df3aa05803425ef0ffec49f39bbae19fba076f38",
          "sha256": "6ec51ce9bf6e1e74503b65ca0945559639eac58a0a8048c75e53c1dce7321eb6",
          "sha1": "2a181b89e86ac649536f32e20e7d40838b767cbd",
          "md5": "5c8782bdc459e5f221e8c89b8e507714"
        }
      ],
      "capabilities": [
        {
          "group": "com.example",
          "name": "greeting",
          "version": "1.0"
        }
      ]
    }
  ]
}
